### ISSUE TITLE
New version of yaml cpp causes build failures

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_calibration#30]
The new API of yaml cpp is not backwards compatible.  It appears Ubuntu 14.04 uses this new version.  As a result, the calibration library will not compile under Indigo/14.04.  Move detailed info can be found [here](https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/HMQL3JzPb_A).

**Comment by davetcoleman** [comment]
Any updates on this for supporting indigo/ubuntu 14.04?

**Comment by andreasBihlmaier** [comment]
The indigo-devel branch works for me without any issues on 14.04(.2)/Indigo.

**Comment by davetcoleman** [comment]
Ah yes, it does compile now! I hadn't installed glog/gflags/ceres.

I think this issue needs to be closed.

**Comment by ghanimmukhtar** [comment]
@shaun-edwards  
I am trying to build the indigo-devel in trusty 14.04 and I have run into the problem with the API of yaml-cpp as an example:
```
/home/ghanim/in_catkin_ws/src/industrial_calibration/industrial_extrinsic_cal/src/targets_yaml_parser.cpp:70:27: error: no match for ‘operator>>’ (operand types are ‘const YAML::Node’ and ‘unsigned int’)
       node["target_type"] >> temp_target->target_type_;
```
and a lot more of the same kind of error. So I was wondering if there is any work around this?

**Comment by shaun-edwards** [comment]
@drchrislewis, any insight into @ghanimmukhtar's issue?

**Comment by drchrislewis** [comment]
@shaun-edwards @ghanimmukhtar 
There is a pull request that unifies the parser for both indigo-devel and hydro-devel. All differences in parsing are contained in one include file "yaml_utils.h." Both repos contain yaml_utils_indigo.h and yaml_utils_hydro.h to make it easier to keep both repos identical except for the parser for a while.

**Comment by ghanimmukhtar** [comment]
@shaun-edwards, @drchrislewis
So I downloaded the zip in the "generalized_parser" branch which contains the "yaml_utils.h" in the include directory of "industrial_extrinsic_cal", and try a catkin_make but still get the same type of errors: 
```/home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/include/industrial_extrinsic_cal/yaml_utils.h:35:22: error: no match for ‘operator>>’ (operand types are ‘const YAML::Node’ and ‘unsigned int’)
       node[var_name] >> var_value;
                      ^
/home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/include/industrial_extrinsic_cal/yaml_utils.h:44:22: note: candidates are:
In file included from /usr/include/boost/detail/container_fwd.hpp:96:0,
                 from /usr/include/boost/functional/hash/extensions.hpp:17,
                 from /usr/include/boost/functional/hash/hash.hpp:529,
                 from /usr/include/boost/functional/hash.hpp:6,
                 from /usr/include/boost/unordered/unordered_map.hpp:20,
                 from /usr/include/boost/unordered_map.hpp:16,
                 from /opt/ros/indigo/include/tf/tf.h:44,
                 from /opt/ros/indigo/include/tf/transform_listener.h:38,
                 from /home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/include/industrial_extrinsic_cal/ros_transform_interface.h:24,
                 from /home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/src/targets_yaml_parser.cpp:9:
/usr/include/c++/4.8/bitset:1453:5: note: template<class _CharT, class _Traits, unsigned int _Nb> std::basic_istream<_CharT, _Traits>& std::operator>>(std::basic_istream<_CharT, _Traits>&, std::bitset<_Nb>&)
     operator>>(std::basic_istream<_CharT, _Traits>& __is, bitset<_Nb>& __x)
     ^
/home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/include/industrial_extrinsic_cal/yaml_utils.h:44:25: note:   types ‘std::basic_istream<_CharT, _Traits>’ and ‘const YAML::Node’ have incompatible cv-qualifiers
       node[var_name] >> var_value;
                         ^
In file included from /usr/include/c++/4.8/iostream:40:0,
                 from /home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/src/targets_yaml_parser.cpp:4:
/usr/include/c++/4.8/istream:779:5: note: template<class _Traits> std::basic_istream<char, _Traits>& std::operator>>(std::basic_istream<char, _Traits>&, signed char*)
     operator>>(basic_istream<char, _Traits>& __in, signed char* __s)
     ^
/home/ghanim/in_catkin_ws/src/industrial_calibratin/industrial_extrinsic_cal/include/industrial_extrinsic_cal/yaml_utils.h:52:13: error: ‘const class YAML::Node’ has no member named ‘FindValue’
     if(node.FindValue(var_name)){
             ^
```
So I am wondering, what is missing?

**Comment by drchrislewis** [comment]
@ghanimmukhtar were you able to locate the two files yaml_utils_hydro.h and yaml_utils_indigo.h?
If so, copy one or the other to yaml_utils.h, and try to re-compile. My understanding is that the new yaml parser for 14.04 and indigo uses the syntax from yaml_utils_indigo.h while the old uses the yaml_utils_hyrdro.h. I have always found this to be true, but perhaps your install of 14.04 has the old yaml library.

**Comment by ghanimmukhtar** [comment]
@drchrislewis 
So now I can compile, what happened was as follows: in the beginning I cloned the packages for "indigo-devel" branch directly and tried to compile, after solving some other problems related to  "cmake_modules" in "industrial_extrinsic_cal" & "target_finder" CMakeList and package files, and 
the issue with the order of (${CERES_LIBRARIES}) and (${catkin_LIBRARIES}) in the linking for (mono_ex_cal) I finally got stuck with the problem in hand about yaml API. Furthermore in this repos, there are no yaml_utils files, neither the general one nor the hydro or indigo ones in the include directory of "industrial_extrinsic_cal". So as mentioned before I tried to compile with the packages from the pull branch "generalized_parser" which has "yaml_utils.h" only but it didn't work. Finally I downloaded the zip file from the pull branch "indigo_devel", which has "yaml_utils.h", "yaml_utils_hydro.h" and "yaml_utils_indigo.h", I kept everything as it is and build and it was successful. 

A small remark about this package: it has a sub-package "rgbd_depth_correction", which produces an
error regarding a referenced header that doesn't yet exist (target_locater.h), so for me and since I don't need this sub-package I simply delete it and everything is compiling nicely now. 

Thanks very much for the help.
