### ISSUE TITLE
Code ported from CERES not correctly licensed

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_calibration#35]
A small bit of code was ported from CERES ([here](https://github.com/ros-industrial/industrial_calibration/blob/hydro-devel/industrial_extrinsic_cal/src/basic_types.cpp#L37-L74)).

Because CERES is BSD licensed and industrial_calibration is Apache 2.0 licensed , there is a conflict.  If the CERES code is required, then it must be isolated in it's own source file with the original CERES BSD license header.

The repo license must also be updated to reflect the multiple licenses.

**Comment by drchrislewis** [comment]
Next pull request will replace code with direct call to ceres::RotationMatrixToAngleAxis() and
ceres::AngleAxisToRotation() rather than duplicating their functionality. This will be a bit slower, but will not have the licensing issues. The code already depends on Ceres, so no additional dependencies were involved.
