### ISSUE TITLE
Extrinsic calibration depricated?

### ISSUE THREAD

**Issue by schelian** [ros-industrial/industrial_calibration#70]
Hi all, the tutorial on extrinsic calibration (http://wiki.ros.org/industrial_extrinsic_cal/Tutorials/Camera%20to%20Target) is deprecated.  It refers to files that do not exist--e.g., cell_calibration.launch & world_to_target_tf.launch.  I can find some of the files (world_to_target_tf.launch) in a hdyro version of the code but not all the files (cell_calibration.launch) and I'm using ROS indigo now.

May I know how people are doing their extrinsic calibration these days?  (Sorry if this question is that of a n00b.)

**Comment by VictorLamoine** [comment]
The extrinsic calibration is not deprecated but the tutorials are out-dated.
You can look at [godel](https://github.com/ros-industrial-consortium/godel) project for an example of how the calibration is done.

A good start is looking at [godel_robots](https://github.com/ros-industrial-consortium/godel/tree/indigo-devel/godel_robots).

**Comment by drchrislewis** [comment]
@AustinDeric There is a working example of using the kinetic-devel branch of both
industrial_calibration_tutorials and industrial_calibration
"roslaunch ind_cal_multi_camera calibrate_from_images.launch" 
We will not likely get to a line by line procedure for calibrating a camera to the robot its mounted on because that involves setting up lots of stuff including moveit with appropriate hooks for modifying the transforms being calibrated.

**Comment by drchrislewis** [comment]
@schelian There is a simple working example under industrial_calibration_tutorials that runs under the kinetic-devel branch(calibrate_from_images.launch). Other tutorials may also be made to run, but require modifications.  These examples are used in training exercises and only updated as necessary for each class to match the hardware and current state of the library.
